// ═══════════════════════════════════════════════════════════════
// DEPENDENCY CONTRACT (8.4.0-P17WI-AAA)
// ═══════════════════════════════════════════════════════════════
// MODULE: ticker.ui.render-enterprise
// PURPOSE: Ticker Renderer Enterprise (DOM Factory)
// ───────────────────────────────────────────────────────────────
// IMPORTS:
//   createUiPorts from /core/runtime/ports-profiles.js
//   getSpeedInSeconds from ../config/design-tokens.js
//
// PROVIDES:
//   VERSION — module constant
//   injectPorts() — exported function
//   getPorts() — exported function
//   getVersion() — exported function
//
// RECEIVES (via init/options): (see init function if present)
// EMITS (eventos):
//   (none)
// LISTENS (eventos):
//   (none)
// WINDOW ACCESS:
//   (none)
// ═══════════════════════════════════════════════════════════════
'use strict';
import { createUiPorts } from '/core/runtime/ports-profiles.js';
import { getSpeedInSeconds } from '../config/design-tokens.js';
export const VERSION = '8.4.0-P17WI';
export const MODULE_ID = 'ticker.ui.render-enterprise';
const hasWindow = typeof window !== 'undefined';
const hasDocument = typeof document !== 'undefined';
const Ports = createUiPorts({ moduleId: MODULE_ID });
function _initPorts() { Ports.init(); }
function _getPort(name: string) { return Ports.get(name); }
export function injectPorts(p: Record<string, unknown>) { return Ports.inject(p); }
export function getPorts() { return Ports.snapshot(); }
const _debug = () => { const cfg = _getPort('config'); return cfg?.app?.debug ?? false; };
const _log = (level: string, ...args: unknown[]) => { const logger = _getPort('logger'); if (!logger) return; if (!_debug() && level === 'debug') return; const fn = logger[level] || logger.info; if (typeof fn === 'function') fn(`[${MODULE_ID}]`, ...args); };
const CATEGORY_ICONS = { breaking: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>', economia: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 3v18h18"/><path d="M18 17V9"/><path d="M13 17V5"/><path d="M8 17v-3"/></svg>', politica: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18"/><path d="M5 21V7l8-4v18"/><path d="M19 21V11l-6-4"/><path d="M9 9v.01"/><path d="M9 12v.01"/><path d="M9 15v.01"/><path d="M9 18v.01"/></svg>', tecnologia: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="16" height="16" rx="2"/><rect x="9" y="9" width="6" height="6"/><path d="M9 1v3"/><path d="M15 1v3"/><path d="M9 20v3"/><path d="M15 20v3"/><path d="M20 9h3"/><path d="M20 14h3"/><path d="M1 9h3"/><path d="M1 14h3"/></svg>', geral: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>' };
const MARKET_ICONS = { fx: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 6v12"/><path d="M6 12h12"/></svg>', stock: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/></svg>', stockDown: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 17 13.5 8.5 8.5 13.5 2 7"/><polyline points="16 17 22 17 22 11"/></svg>' };
const SOURCE_ICONS = { g1: '<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><text x="2" y="17" font-size="14" font-weight="bold" font-family="Arial">G1</text></svg>', uol: '<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="12" r="8" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="3"/></svg>', folha: '<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><rect x="4" y="4" width="16" height="16" rx="2" fill="none" stroke="currentColor" stroke-width="2"/><line x1="8" y1="9" x2="16" y2="9" stroke="currentColor" stroke-width="2"/><line x1="8" y1="13" x2="14" y2="13" stroke="currentColor" stroke-width="1.5"/></svg>', estadao: '<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><text x="4" y="16" font-size="12" font-weight="bold" font-family="serif">E</text></svg>', valor: '<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M4 4l8 16 8-16" fill="none" stroke="currentColor" stroke-width="2"/></svg>', default: '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/></svg>' };
export class TickerRendererEnterprise {
  [key: string]: any;
  constructor(container: unknown, store: unknown, configStore: unknown) { this.container = container; this.store = store; this.configStore = configStore; this.track = null; this.unsubscribe = null; this._metrics = { renderCount: 0, configApplyCount: 0, lastRenderAt: null }; }
  init() { this.track = this.container.querySelector('.ticker-track'); if (this.configStore) { this.unsubscribe = this.configStore.subscribe((config: Record<string, any>) => { this.applyConfig(config); }); } _log('debug', 'Renderer initialized'); }
  render() { if (!this.track) return; const { news, status } = this.store.getState(); const config = this.configStore ? this.configStore.getConfig() : this._getDefaultConfig(); if (status === 'loading') { this._renderLoading(); } else if (status === 'offline') { this._renderOffline(); } else if (news && news.length > 0) { this._renderItems(news, config); } this._metrics.renderCount++; this._metrics.lastRenderAt = Date.now(); }
  // @ts-expect-error strict migration — TS2345
  _renderLoading() { this._clearTrack(); if (!hasDocument) return; const span = document.createElement('span'); span.className = 'ticker-loading'; const svg = this._createSVG('spinner'); span.appendChild(svg); span.appendChild(document.createTextNode('Carregando dados...')); this.track.appendChild(span); }
  // @ts-expect-error strict migration — TS2345
  _renderOffline() { this._clearTrack(); if (!hasDocument) return; const span = document.createElement('span'); span.className = 'ticker-offline'; const svg = this._createSVG('alert'); span.appendChild(svg); span.appendChild(document.createTextNode('Sem conexao')); this.track.appendChild(span); }
  // @ts-expect-error strict migration — TS2345
  _renderItems(items: unknown[], config: Record<string, any>) { this._clearTrack(); if (!hasDocument) return; const baseItems = Array.isArray(items) ? [...items] : []; const MIN_ITEMS = 6; const extendedItems = []; while (extendedItems.length < MIN_ITEMS && baseItems.length > 0) { extendedItems.push(...baseItems); } if (extendedItems.length === 0) { this._renderEmpty(); return; } const fragment = document.createDocumentFragment(); extendedItems.forEach((item, index) => { const node = this._createItemNode(item, config, index); fragment.appendChild(node); fragment.appendChild(this._createSeparator(config.visual?.separatorStyle || 'minimal')); }); const fragmentClone = fragment.cloneNode(true); this.track.appendChild(fragment); this.track.appendChild(fragmentClone); }
  _renderEmpty() { this._clearTrack(); if (!hasDocument) return; const span = document.createElement('span'); span.className = 'ticker-offline'; span.textContent = 'Nenhum dado disponivel'; this.track.appendChild(span); }
  _createItemNode(item: Record<string, any>, config: Record<string, any>, index: number) { const type = item.type || 'news'; const variant = (index % 3) + 1; switch (type) { case 'fx': return this._createFXNode(item, config, variant); case 'stock': return this._createStockNode(item, config, variant); default: return this._createNewsNode(item, config, variant); } }
  _createNewsNode(item: Record<string, any>, config: Record<string, any>, variant: number) { if (!hasDocument) return null; const category = this._detectCategory(item.title || ''); const isBreaking = category === 'breaking'; const time = this._formatTime(item.published_at || item.pubDate); const source = item.source || 'default'; const wrapper = document.createElement('div'); wrapper.className = ['ticker-item', 'ticker-item--news', `ticker-item--variant-${variant}`, `ticker-item--categoria-${category}`, isBreaking ? 'ticker-item--breaking' : ''].filter(Boolean).join(' '); const sourceIcon = document.createElement('span'); sourceIcon.className = 'ticker-source-icon'; sourceIcon.title = source; sourceIcon.innerHTML = (SOURCE_ICONS as Record<string, string>)[source] || SOURCE_ICONS.default; wrapper.appendChild(sourceIcon); const timeSpan = document.createElement('span'); timeSpan.className = 'ticker-time'; timeSpan.textContent = time; wrapper.appendChild(timeSpan); const link = document.createElement('a'); link.href = item.url || '#'; link.target = '_blank'; link.rel = 'noopener noreferrer'; link.className = 'ticker-title'; link.textContent = item.title || ''; wrapper.appendChild(link); if (config.visual?.showTag !== false) { const tag = document.createElement('span'); tag.className = 'ticker-tag'; tag.textContent = this._getCategoryLabel(category); wrapper.appendChild(tag); } return wrapper; }
  _createFXNode(item: Record<string, any>, config: Record<string, any>, variant: number) { if (!hasDocument) return null; const change = item.change_pct || 0; const changeClass = change === 0 ? 'neutral' : (change > 0 ? 'positive' : 'negative'); const changeSign = change > 0 ? '+' : ''; const price = this._formatPrice(item.price, 2); const wrapper = document.createElement('div'); wrapper.className = ['ticker-item', 'ticker-item--fx', `ticker-item--variant-${variant}`, `ticker-item--${changeClass}`].join(' '); const icon = document.createElement('span'); icon.className = 'ticker-market-icon'; icon.innerHTML = MARKET_ICONS.fx; wrapper.appendChild(icon); const symbol = document.createElement('span'); symbol.className = 'ticker-symbol'; symbol.textContent = item.symbol || 'FX'; wrapper.appendChild(symbol); const priceSpan = document.createElement('span'); priceSpan.className = 'ticker-price'; priceSpan.textContent = price; wrapper.appendChild(priceSpan); const changeSpan = document.createElement('span'); changeSpan.className = `ticker-change ticker-change--${changeClass}`; changeSpan.textContent = `${changeSign}${change.toFixed(2)}%`; wrapper.appendChild(changeSpan); return wrapper; }
  _createStockNode(item: Record<string, any>, config: Record<string, any>, variant: number) { if (!hasDocument) return null; const change = item.change_pct || 0; const isPositive = change > 0; const changeClass = change === 0 ? 'neutral' : (isPositive ? 'positive' : 'negative'); const changeSign = isPositive ? '+' : ''; const price = this._formatPrice(item.price, 2); const wrapper = document.createElement('div'); wrapper.className = ['ticker-item', 'ticker-item--stock', `ticker-item--variant-${variant}`, `ticker-item--${changeClass}`].join(' '); const icon = document.createElement('span'); icon.className = 'ticker-market-icon'; icon.innerHTML = isPositive ? MARKET_ICONS.stock : MARKET_ICONS.stockDown; wrapper.appendChild(icon); const symbol = document.createElement('span'); symbol.className = 'ticker-symbol'; symbol.textContent = item.symbol || 'STOCK'; wrapper.appendChild(symbol); const priceSpan = document.createElement('span'); priceSpan.className = 'ticker-price'; priceSpan.textContent = `R$ ${price}`; wrapper.appendChild(priceSpan); const changeSpan = document.createElement('span'); changeSpan.className = `ticker-change ticker-change--${changeClass}`; changeSpan.textContent = `${changeSign}${change.toFixed(2)}%`; wrapper.appendChild(changeSpan); return wrapper; }
  _createSeparator(style: string) { if (!hasDocument) return null; const span = document.createElement('span'); const styles: Record<string, string[]> = { bullet: ['ticker-separator', 'ticker-separator--bullet'], bar: ['ticker-separator', 'ticker-separator--bar'], chevron: ['ticker-separator', 'ticker-separator--chevron'], minimal: ['ticker-separator', 'ticker-separator--minimal'] }; span.className = (styles[style] || styles.minimal).join(' '); if (style === 'bullet') span.textContent = '•'; if (style === 'chevron') span.textContent = '›'; return span; }
  _createSVG(type: string) { if (!hasDocument) return null; const wrapper = document.createElement('span'); if (type === 'spinner') { wrapper.innerHTML = '<svg class="ticker-loading-spinner" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12a9 9 0 1 1-6.219-8.56"/></svg>'; } else if (type === 'alert') { wrapper.innerHTML = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>'; } return wrapper.firstChild; }
  _clearTrack() { if (this.track) { this.track.replaceChildren(); } }
  _formatTime(dateStr: string) { if (!dateStr) return '--:--'; try { const date = new Date(dateStr); return date.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }); } catch (e) { return '--:--'; } }
  _formatPrice(price: unknown, decimals: number = 2) { if (price === null || price === undefined) return '--'; return Number(price).toLocaleString('pt-BR', { minimumFractionDigits: decimals, maximumFractionDigits: decimals }); }
  _getCategoryLabel(category: string) { const labels: Record<string, string> = { breaking: 'URGENTE', economia: 'ECON', politica: 'POL', tecnologia: 'TECH', geral: 'GERAL' }; return labels[category] || 'GERAL'; }
  _detectCategory(title: string) { const lower = title.toLowerCase(); if (lower.includes('urgente') || lower.includes('breaking') || lower.includes('ultima hora') || lower.includes('alerta')) return 'breaking'; if (lower.includes('economia') || lower.includes('mercado') || lower.includes('dolar') || lower.includes('bolsa') || lower.includes('ibovespa') || lower.includes('inflacao') || lower.includes('pib') || lower.includes('selic')) return 'economia'; if (lower.includes('politica') || lower.includes('eleicao') || lower.includes('governo') || lower.includes('congresso') || lower.includes('senado') || lower.includes('lula') || lower.includes('ministro')) return 'politica'; if (lower.includes('tecnologia') || lower.includes('tech') || lower.includes('ia') || lower.includes('inteligencia artificial') || lower.includes('startup') || lower.includes('apple') || lower.includes('google')) return 'tecnologia'; return 'geral'; }
  _getDefaultConfig() { return { visual: { height: 'default', fontSize: 'medium', showTag: true, separatorStyle: 'minimal' }, theme: { background: 'darkA' }, behavior: { speed: 'medium', direction: 'left' }, accessibility: { highContrast: false, respectReducedMotion: true } }; }
  applyConfig(config: Record<string, any>) { if (!this.container) return; this.container.classList.remove('ticker--height-compact', 'ticker--height-default', 'ticker--height-tall'); this.container.classList.add(`ticker--height-${config.visual?.height || 'default'}`); this.container.classList.remove('ticker--font-small', 'ticker--font-medium', 'ticker--font-large'); this.container.classList.add(`ticker--font-${config.visual?.fontSize || 'medium'}`); this.container.dataset.theme = config.theme?.background || 'darkA'; this.container.dataset.highContrast = config.accessibility?.highContrast ? 'true' : 'false'; if (this.track) { const speed = getSpeedInSeconds(config.behavior?.speed || 'medium'); this.track.style.animationDuration = `${speed}s`; this.track.style.animationDirection = config.behavior?.direction === 'right' ? 'reverse' : 'normal'; } this.render(); this._metrics.configApplyCount++; _log('debug', 'Config applied'); }
  destroy() { if (this.unsubscribe) { this.unsubscribe(); this.unsubscribe = null; } this.track = null; this.container = null; this.store = null; this.configStore = null; _log('debug', 'Renderer destroyed'); }
  healthCheck() { const logger = _getPort('logger'); const checks = { hasTrack: !!this.track, hasStore: !!this.store, hasConfigStore: !!this.configStore, loggerReady: !!logger, portsInitialized: Ports.isInitialized() }; const passed = Object.values(checks).filter(Boolean).length; return { status: passed === 5 ? 'HEALTHY' : 'DEGRADED', score: `${passed}/5`, checks, version: VERSION, moduleId: MODULE_ID, portsInitialized: Ports.isInitialized(), timestamp: new Date().toISOString() }; }
  info() { return { version: VERSION, moduleId: MODULE_ID, metrics: this._metrics, portsInitialized: Ports.isInitialized(), healthCheck: this.healthCheck() }; }
  getMetrics() { return { ...this._metrics }; }
  resetMetrics() { this._metrics = { renderCount: 0, configApplyCount: 0, lastRenderAt: null }; }
}
export function getVersion() { return VERSION; }
export default TickerRendererEnterprise;
