// ═══════════════════════════════════════════════════════════════
// DEPENDENCY CONTRACT (7.4.0-P17WI)
// ═══════════════════════════════════════════════════════════════
// MODULE: router.registry.definitions.routes-admin
// PURPOSE: Router Definitions - Admin Routes
// ───────────────────────────────────────────────────────────────
// IMPORTS:
//   DOMAINS, LAYOUTS, GUARD_POLICIES from ./constants.js
//
// PROVIDES:
//   adminRoutes — exported value
//   MODULE_ID — module constant
//   VERSION — module constant
//
// RECEIVES (via init/options): (none)
// EMITS (eventos):
//   (none)
// LISTENS (eventos):
//   (none)
// WINDOW ACCESS:
//   (none)
// ═══════════════════════════════════════════════════════════════
'use strict';
const MODULE_ID = 'router.registry.definitions.routes-admin';
const VERSION = '7.4.1-P17WI';
import { DOMAINS, LAYOUTS, GUARD_POLICIES } from './constants.js';
const createAdminRoute = (id: string, title: string, panel: string, options: Record<string, any> = {}) => ({ id, name: title.replace(/\s+/g, ''), page: id, title, public: false, requiresAuth: true, guardPolicy: options.guardPolicy || GUARD_POLICIES.PERMISSIONS, permissions: options.permissions || [], featureFlags: [] as string[], layout: LAYOUTS.DEFAULT, defaultView: panel, defaultHash: `#/${id}`, panel, mountMain: true, domain: DOMAINS.ADMIN, virtualDefaults: { view: panel, tab: (options.tab || 'overview') as string, section: null as string | null, entity: (options.entity || null) as string | null, mode: (options.mode || 'view') as string }, seo: { title: `DshowDash - ${title}`, description: options.description || title }, aliases: options.aliases || [], tags: ['admin', ...(options.tags || [])] });
const createUserRoute = (id: string, title: string, panel: string, options: Record<string, any> = {}) => ({ id, name: title.replace(/\s+/g, ''), page: id, title, public: false, requiresAuth: true, guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: options.permissions || [], featureFlags: [] as string[], layout: LAYOUTS.DEFAULT, defaultView: panel, defaultHash: `#/${id}`, panel, mountMain: true, domain: DOMAINS.ADMIN, virtualDefaults: { view: panel, tab: (options.tab || 'overview') as string, section: null as string | null, entity: (options.entity || null) as string | null, mode: (options.mode || 'view') as string }, seo: { title: `DshowDash - ${title}`, description: options.description || title }, aliases: options.aliases || [], tags: ['user', ...(options.tags || [])] });
export const adminRoutes = Object.freeze({
  '/admin/usuarios': { id: 'admin-usuarios', name: 'AdminUsuarios', page: 'admin-usuarios', title: 'Gestão de Usuários', public: false, requiresAuth: true, guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: ['role:admin', 'role:super_admin'], featureFlags: [] as string[], layout: LAYOUTS.DEFAULT, defaultView: 'panel-user-management', defaultHash: '#/panel-user-management', panel: 'panel-user-management', mountMain: true, domain: DOMAINS.ADMIN, virtualDefaults: { view: 'panel-user-management', tab: 'list', section: null as string | null, entity: 'user', mode: 'view' }, seo: { title: 'Gestão de Usuários', description: 'Gerenciamento de usuários do sistema' }, aliases: ['/admin/users', '/usuarios', '/user-management'], tags: ['admin', 'users', 'enterprise'] },
  '/admin/permissoes': { id: 'admin-permissoes', name: 'AdminPermissoes', page: 'admin-permissoes', title: 'Roles e Permissões', public: false, requiresAuth: true, guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: ['role:super_admin'], featureFlags: [] as string[], layout: LAYOUTS.DEFAULT, defaultView: 'panel-permissions-admin', defaultHash: '#/panel-permissions-admin', panel: 'panel-permissions-admin', mountMain: true, domain: DOMAINS.ADMIN, virtualDefaults: { view: 'panel-permissions-admin', tab: 'roles', section: null as string | null, entity: 'role', mode: 'view' }, seo: { title: 'Roles e Permissões', description: 'Administração de roles e permissões' }, aliases: ['/admin/permissions', '/admin/roles', '/permissions-admin'], tags: ['admin', 'permissions', 'enterprise', 'security'] },
  '/admin/sessoes': { id: 'admin-sessoes', name: 'AdminSessoes', page: 'admin-sessoes', title: 'Gerenciamento de Sessões', public: false, requiresAuth: true, guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: ['role:manager', 'role:admin', 'role:super_admin'], featureFlags: [] as string[], layout: LAYOUTS.DEFAULT, defaultView: 'panel-session-admin', defaultHash: '#/panel-session-admin', panel: 'panel-session-admin', mountMain: true, domain: DOMAINS.ADMIN, virtualDefaults: { view: 'panel-session-admin', tab: 'active', section: null as string | null, entity: 'session', mode: 'view' }, seo: { title: 'Sessões', description: 'Visualização e gerenciamento de sessões ativas' }, aliases: ['/admin/sessions', '/session-admin'], tags: ['admin', 'sessions', 'enterprise', 'security'] },
  '/admin/feature-flags': { id: 'admin-feature-flags', name: 'AdminFeatureFlags', page: 'admin-feature-flags', title: 'Feature Flags', public: false, requiresAuth: true, guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: ['role:admin', 'role:super_admin'], featureFlags: [] as string[], layout: LAYOUTS.DEFAULT, defaultView: 'panel-feature-flags-admin', defaultHash: '#/panel-feature-flags-admin', panel: 'panel-feature-flags-admin', mountMain: true, domain: DOMAINS.ADMIN, virtualDefaults: { view: 'panel-feature-flags-admin', tab: 'list', section: null, entity: 'flag', mode: 'view' }, seo: { title: 'Feature Flags', description: 'Gerenciamento de feature flags do sistema' }, aliases: ['/admin/flags', '/feature-flags'], tags: ['admin', 'feature-flags', 'enterprise', 'devops'] },
  '/admin/auditoria': { id: 'admin-auditoria', name: 'AdminAuditoria', page: 'admin-auditoria', title: 'Auditoria e Logs', public: false, requiresAuth: true, guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: ['role:manager', 'role:admin', 'role:super_admin'], featureFlags: [] as string[], layout: LAYOUTS.DEFAULT, defaultView: 'panel-audit-trail', defaultHash: '#/panel-audit-trail', panel: 'panel-audit-trail', mountMain: true, domain: DOMAINS.ADMIN, virtualDefaults: { view: 'panel-audit-trail', tab: 'logs', section: null, entity: 'audit', mode: 'view' }, seo: { title: 'Auditoria', description: 'Trail de auditoria e logs do sistema' }, aliases: ['/admin/audit', '/auditoria', '/audit-trail'], tags: ['admin', 'audit', 'enterprise', 'security', 'logs'] },
  '/admin/navegacao': { id: 'admin-navegacao', name: 'AdminNavegacao', page: 'admin-navegacao', title: 'Administração de Navegação', public: false, requiresAuth: true, guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: ['role:super_admin'], featureFlags: [] as string[], layout: LAYOUTS.DEFAULT, defaultView: 'panel-nav-admin', defaultHash: '#/panel-nav-admin', panel: 'panel-nav-admin', mountMain: true, domain: DOMAINS.ADMIN, virtualDefaults: { view: 'panel-nav-admin', tab: 'items', section: null, entity: 'nav-item', mode: 'view' }, seo: { title: 'Administração de Navegação', description: 'Gerenciamento de itens e seções da sidebar' }, aliases: ['/admin/navigation', '/nav-admin', '/navegacao'], tags: ['admin', 'navigation', 'sidebar', 'enterprise'] },
  '/preferencias': { id: 'preferencias', name: 'Preferencias', page: 'preferencias', title: 'Minhas Preferências', public: false, requiresAuth: true, guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: [] as string[], featureFlags: [] as string[], layout: LAYOUTS.DEFAULT, defaultView: 'panel-user-preferences', defaultHash: '#/panel-user-preferences', panel: 'panel-user-preferences', mountMain: true, domain: DOMAINS.ADMIN, virtualDefaults: { view: 'panel-user-preferences', tab: 'general', section: null, entity: null as string | null, mode: 'edit' }, seo: { title: 'Preferências', description: 'Configurações pessoais e preferências' }, aliases: ['/preferences', '/user-preferences', '/minha-conta'], tags: ['user', 'preferences', 'profile'] },
  // COMPATIBILIDADE (2026-09-14): rota registrada no banco (app_nav_route admin/gestao-paineis → panel-gestao-paineis; ui_nav_items
  // sidebar.admin.gestao-paineis) que não existia no registro do código — a navegação por hash caía no 1º segmento.
  '/admin/gestao-paineis': createAdminRoute('admin-gestao-paineis', 'Gestão de Painéis', 'panel-gestao-paineis', { guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: ['role:admin', 'role:super_admin'], tags: ['admin', 'paineis', 'gestao'], description: 'Gestao e monitoramento dos paineis (registro, screenshots)' }),
  '/admin-users': createAdminRoute('admin-users', 'Gestão de Usuários', 'panel-user-management', { guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: ['role:admin'], entity: 'user', tab: 'list', tags: ['users', 'enterprise'] }),
  '/admin-settings': createAdminRoute('admin-settings', 'Configurações Admin', 'panel-nav-admin', { guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: ['role:admin'], tags: ['settings', 'config'] }),
  // COMPATIBILIDADE (2026-09-16, rotas históricas): /profile e /settings são paths antigos do header ("Profile (Header)" /
  // "Settings (Header)" em app_nav_route, 2025-12); o header atual usa #/meu-perfil e o painel de preferências por ação, sem
  // passar por eles. /settings = alias histórico de /preferencias (mesmo painel). /profile: com as6.profile_redirect ON (100%
  // desde 12/09) o shim components/router/profile-redirect leva #/profile → /panel-avatar-studio por hashchange; o alvo abaixo
  // só vale com a flag OFF (fail-closed). Aposentar flag+shim e retargetar aqui = lote próprio, com GO do dono.
  '/profile': createAdminRoute('profile', 'Meu Perfil', 'panel-user-preferences', { guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: [] as string[], tab: 'profile', mode: 'edit', tags: ['profile', 'user', 'compatibilidade'] }),
  '/settings': createAdminRoute('settings', 'Configurações', 'panel-user-preferences', { guardPolicy: GUARD_POLICIES.PERMISSIONS, permissions: [] as string[], tab: 'settings', mode: 'edit', tags: ['settings', 'user', 'compatibilidade'] }),
  '/meu-perfil': createUserRoute('meu-perfil', 'Meu Perfil', 'panel-user-profile', { permissions: [] as string[], tab: 'profile', mode: 'edit', description: 'Editar informações do perfil', aliases: ['/my-profile', '/perfil'], tags: ['profile', 'account'] }),
  '/seguranca-conta': createUserRoute('seguranca-conta', 'Segurança da Conta', 'panel-account-security', { permissions: [] as string[], tab: 'security', mode: 'edit', description: 'Configurações de segurança e senha', aliases: ['/account-security', '/seguranca'], tags: ['security', 'account', 'password'] }),
  '/notificacoes': createUserRoute('notificacoes', 'Notificações', 'panel-user-notifications', { permissions: [] as string[], tab: 'notifications', mode: 'edit', description: 'Preferências de notificações', aliases: ['/notifications', '/alertas'], tags: ['notifications', 'account'] }),
  '/sessoes-ativas': createUserRoute('sessoes-ativas', 'Sessões Ativas', 'panel-user-sessions', { permissions: [] as string[], tab: 'sessions', mode: 'view', description: 'Gerenciar sessões ativas', aliases: ['/active-sessions', '/minhas-sessoes', '/sessoes'], tags: ['sessions', 'account', 'security'] })
});
export { MODULE_ID, VERSION };
export default adminRoutes;
