#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# BUILD SCRIPT: main.tokens.css
# ═══════════════════════════════════════════════════════════════
# Gera main.tokens.css a partir da fonte canônica modules/01-tokens.css
# + legacy-aliases.css. Zero @import no output.
#
# Fonte canônica: ui/container-main/styles/modules/01-tokens.css
# Legacy aliases: legacy-aliases.css (--main-* aliases de compatibilidade)
# Artefato gerado: main.tokens.css (NÃO editar diretamente)
#
# Uso: bash build-tokens.sh
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CANONICAL_SOURCE="$SCRIPT_DIR/ui/container-main/styles/modules/01-tokens.css"
LEGACY_ALIASES="$SCRIPT_DIR/legacy-aliases.css"
OUTPUT="$SCRIPT_DIR/main.tokens.css"
TIMESTAMP=$(date -Iseconds)

# Validar que a fonte canônica existe
if [ ! -f "$CANONICAL_SOURCE" ]; then
  echo "ERRO: Fonte canônica não encontrada: $CANONICAL_SOURCE"
  exit 1
fi

# Validar que legacy aliases existe
if [ ! -f "$LEGACY_ALIASES" ]; then
  echo "ERRO: Legacy aliases não encontrado: $LEGACY_ALIASES"
  exit 1
fi

# Escrever header do artefato
cat > "$OUTPUT" << 'EOF'
/* Main Tokens CSS - Design Tokens */
/* @generated by build-tokens.sh — NÃO EDITAR DIRETAMENTE */
/* @version 3.1.0-GOVERNED */
/* @canonical-source: ui/container-main/styles/modules/01-tokens.css */
EOF

# Adicionar timestamp (fora do heredoc para expandir variável)
echo "/* @build-timestamp: $TIMESTAMP */" >> "$OUTPUT"

# Linha em branco separando header do conteúdo
echo "" >> "$OUTPUT"

# Concatenar fonte canônica (tokens --cm-*)
cat "$CANONICAL_SOURCE" >> "$OUTPUT"

# Linha em branco antes dos legacy aliases
echo "" >> "$OUTPUT"

# Concatenar legacy aliases (--main-* aliases de compatibilidade)
cat "$LEGACY_ALIASES" >> "$OUTPUT"

# Validação pós-build
LINES=$(wc -l < "$OUTPUT")
BYTES=$(wc -c < "$OUTPUT")
IMPORTS=$(grep -c "@import" "$OUTPUT" 2>/dev/null || true)
CM_TOKENS=$(grep -c "\-\-cm-" "$OUTPUT" 2>/dev/null || true)
MAIN_TOKENS=$(grep -c "\-\-main-" "$OUTPUT" 2>/dev/null || true)

echo "═══════════════════════════════════════════════════════"
echo "BUILD COMPLETO: main.tokens.css"
echo "═══════════════════════════════════════════════════════"
echo "  Fonte canônica: $(basename "$CANONICAL_SOURCE")"
echo "  Legacy aliases: $(basename "$LEGACY_ALIASES")"
echo "  Linhas:  $LINES"
echo "  Bytes:   $BYTES"
echo "  @import: $IMPORTS (deve ser 0)"
echo "  Tokens --cm-*:   $CM_TOKENS"
echo "  Tokens --main-*: $MAIN_TOKENS"
echo "  Timestamp: $TIMESTAMP"
echo "═══════════════════════════════════════════════════════"

if [ "$IMPORTS" -gt 0 ]; then
  echo "ALERTA: Artefato contém @import — verificar fontes!"
  grep -n "@import" "$OUTPUT"
  exit 1
fi

if [ "$CM_TOKENS" -eq 0 ]; then
  echo "ALERTA: Nenhum token --cm-* encontrado — fonte canônica pode estar vazia!"
  exit 1
fi

echo "Validação OK — zero @import, $CM_TOKENS tokens --cm-* presentes."
